### ISSUE TITLE
How to run dynamo_grasp on custom dataset?

### ISSUE THREAD

**Issue by PannagaS** [dynamo-grasp/dynamo-grasp#1]
Hi, thank you for your contribution and this is really an amazing paper. I want to replicate the implementation for my own use case and I want to train the model for my own dataset. I followed the documentation, but I wasn't sure how to re-format the folders to use my dataset. 

<img width="682" alt="image" src="https://github.com/user-attachments/assets/231a3b77-8045-4eb3-b712-4319852e4581">

As per the documentation, there has to be .png files, but I dont see them in the repo. I am also unclear about how I can generate json data. Can someone please help me out here? 

Any help is greatly appreciated. 
Thank you.

**Comment by Soofiyan** [comment]
Hello @PannagaS,
Json files are located in the directory: https://github.com/dynamo-grasp/dynamo-grasp/tree/main/scenario_grasp_configurations
Other data files you can find at: https://github.com/dynamo-grasp/dynamo-grasp/tree/main/docs/src/data/Processed_Data

To collect these data, you have to run the simulation or refer to https://github.com/dynamo-grasp/dynamo-grasp/blob/3ff1ea22a7233f95c70caee2f3c902520b193a6d/isaacgymenvs/tasks/CommonUtils/calculate_error.py

**Comment by PannagaS** [comment]
Thank you for your quick reply @Soofiyan
